name: onlook-dev

services:
  onlook-dev:
    image: ${IMAGE_REGISTRY:-}onlook-web-dev:${IMAGE_TAG:-latest}
    container_name: onlook-web-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    network_mode: host

  onlook-seed:
    image: ${IMAGE_REGISTRY:-}onlook-web-dev:${IMAGE_TAG:-latest}
    working_dir: /app
    env_file:
      - .env
    network_mode: host
    command: bun db:seed
