name: onlook

services:
  web-client:
    image: ${IMAGE_REGISTRY:-}onlook-web:${IMAGE_TAG:-latest}
    container_name: onlook-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    network_mode: host
